### ISSUE TITLE
3.0.4 saved waystones dissapear

### ISSUE THREAD

**Issue by jarocajavi** [LordDeatHunter/FabricWaystones#157]
A tested the last version and i found this issue, the saved waystones dissapears and the "public world button" doesnt work either.
I did a downgrade until your fixed, and for now is work fine.

Thanks for your time!!

**Comment by LordDeatHunter** [comment]
Is it fine on 3.0.3?

**Comment by ImToxik** [comment]
Wanted to reply since OP didn't. I had this issue while running 3.0.4 both client-side and server-side. I swapped the server-side 3.0.4 jar file with the 3.0.3 jar, while leaving 3.0.4 on the client, and it seems to have fixed the issue. So, 3.0.4 server + 3.0.4 client = new waystones don't stay active, and the "Toggle global waystone" button doesn't stay lit up. 3.0.3 server + 3.0.4 client works perfectly fine.

**Comment by jarocajavi** [comment]
> 

yep

**Comment by LordDeatHunter** [comment]
Really stupid issues that I couldn't fix because I was away for 10 days 🤦‍♂️ I'll be making a release shortly, thank you for your patience.
