### ISSUE TITLE
Waystones getting mixed up with oneanother or resetting

### ISSUE THREAD

**Issue by Greg-J** [LordDeatHunter/FabricWaystones#17]
We have Waystones installed on a server and I have about a half dozen discovered. They are now all mixed up. None of the ones I named take me to the right place, one of them reverted back to its original name, and one of them I can't even get to now.

**Comment by Prophious** [comment]
i have the same issue, mine is on a private server, where i do have access to the files.... 

my issue is mostly where one waystone location is still there and several of them just send me to a random other discovered waystone

**Comment by CmdrJane** [comment]
Still happens in the latest version

**Comment by Greg-J** [comment]
I don't understand how a bug like this exists...

**Comment by Tsudico** [comment]
Just from a brief look at the code, it appears the dat file (waystone database) is set to use the waystone name as it's id for waystones. This doesn't seem like a good idea since the name of the waystone can change. It would be better for the waystone to use the location of the waystone (x,y,z combined by hash?) so that it is unique and doesn't change over the lifetime of the waystone:
```java
                String id;
                if (waystone != null) {
                    id = waystone.name;
                } else {
                    id = Utils.generateWaystoneName("");
                }
```
Has anyone experienced the problem of mixed up waystones without changing the original name of any of the waystones?

**Comment by LordDeatHunter** [comment]
Does anyone have a server or something I can test this on? I've tried multiple times but I haven't been able to recreate the bug.
My discord is DH#9367

**Comment by LordDeatHunter** [comment]
Fixed 👍
